name: Swift

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: clone swift-format
        run: |
          git clone -b swift-5.2-branch git://github.com/apple/swift-format

      - name: cache swift-format
        uses: actions/cache@v1.1.2
        with:
          path: swift-format/.build
          key: ${{ runner.os }}-swift-format-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-format-

    - name: build swift-format
      run: |
        cd swift-format
        swift build -c release
        echo "::add-path::${PWD}/.build/release"
        cd ..

    - name: lint
      uses: compnerd/lint-action@s4tf
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        auto_fix: true
        appleswiftformat: true

  # build:
  #
  #  runs-on: macos-latest
  #
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Build
  #    run: swift build -v
  #  - name: Run tests
  #    run: swift test -v
